* Configuration summary table

config_v00: Nominal Run 1A geometry
config_v03: 1/4" Al plate target. No COL5, IPA, OPA, or original target. 
config_v06: 2 cm Al plate target, 10 cm poly shield. No COL5, IPA, OPA, or original target. 
config_v10: 2 cm Al plate target, 5 cm poly shield. No COL5, IPA, OPA, or original target. 
config_v11: 2 cm Al plate target, 1 cm poly shield. No COL5, IPA, OPA, or original target. 
config_v12: 2 cm Al plate target, no poly shield. No COL5, IPA, OPA, or original target. 
config_v13: 1.3 cm Al plate target, 1 cm poly shield. No COL5, IPA, OPA, or original target. 
config_v14: 2 cm Al plate target, 25 mm hole, no poly shield. No COL5. IPA, OPA, and original target included.
config_v15: 2 cm Al plate target, no poly shield. Added COL5. No IPA, OPA, or original target. 
config_v16: 2 cm target on the degrader, 150 mm radius, no poly shield. COL5, IPA, OPA, and original target included. 
config_v17: 2 cm target on the degrader, 300 mm radius, no poly shield. COL5, IPA, OPA, and original target included. 
config_v18: 2 cm Al plate target, no poly shield. Added COL5. No IPA, OPA, and original target. 
config_v19: 2 cm Al plate target, 25 mm hole with 3 mm thick aluminum fill, no poly shield. No Col5, IPA, OPA, or original target.
config_v20: 2 cm Al plate target, 25 mm hole with 3 mm thick aluminum fill, no poly shield. Added COL5. No IPA, OPA, or original target.
config_v21: 2 cm Al plate target, 50 mm hole with 3 mm thick aluminum fill, no poly shield. Added COL5. No IPA, OPA, or original target.
config_v22: 2 cm target on the degrader, 150 mm radius, no poly shield. Al plate with 75 mm hole. COL5, IPA, OPA, and original target included. 
config_v23: 2 cm target on the degrader, 150 mm radius, no poly shield. Al plate with 100 mm hole. COL5, IPA, OPA, and original target included. 
config_v24: 2 cm target on the degrader, 150 mm radius, no poly shield. Al plate with 125 mm hole. COL5, IPA, OPA, and original target included. 
|-----------------+------+----------+-------+------------------+----------+-----------+----------+----------+--------+----------+------------+-----------|
| Config          |  Run |   Target |  Poly |   Hole radius    | Mu stop  | Calo stop | RMC eff  |  CE eff  | CE MPV |  Run 1A  |   Run 1A   | Run 1A CE |
|                 |      |          |       |                  | per POT  |  per POT  | Edep(50) | Edep(50) |        |  CE eff  | CE Trk MPV | S/sqrt(B) |
|-----------------+------+----------+-------+------------------+----------+-----------+----------+----------+--------+----------+------------+-----------|
| v00             | 1400 |    Foils |  None |      Normal      | 4.64e-06 | 2.45e-05  | 7.72e-09 | 8.44e-09 |  -6.25 | 3.73e-04 |   -0.46    |           |
|-----------------+------+----------+-------+------------------+----------+-----------+----------+----------+--------+----------+------------+-----------|
| v03             | 1450 | 0.635 cm |  None |       None       | 9.62e-04 | 1.24e-05  | 1.02e-06 | 1.18e-06 |  -6.18 | 2.79e-04 |   -2.04    |           |
| v06             | 1460 |     2 cm | 10 cm |       None       | 1.29e-03 | 0.00e-00  | 1.19e-06 | 9.07e-07 |  -36.2 | 6.23e-06 |   -48.0    |           |
| v10             | 1470 |     2 cm |  5 cm |       None       | 1.29e-03 | 0.00e-00  | 1.33e-06 | 1.27e-06 |  -22.1 | 3.25e-05 |   -29.9    |           |
| v11             | 1471 |     2 cm |  1 cm |       None       | 1.29e-03 | 2.13e-07  | 1.30e-06 | 1.41e-06 |  -13.2 | 1.00e-04 |   -16.5    |           |
| v12             | 1472 |     2 cm |  0 cm |       None       | 1.30e-03 | 6.82e-07  | 1.31e-06 | 1.44e-06 |  -11.1 | 1.03e-04 |   -10.8    |           |
| v13             | 1473 |   1.3 cm |  1 cm |       None       | 1.19e-03 | 1.49e-06  | 1.25e-06 | 1.41e-06 |  -10.0 | 1.44e-04 |    -9.7    |           |
| v14             | 1474 |     2 cm |  0 cm |      25 mm       | 1.28e-03 | 1.66e-06  | 1.34e-06 | 1.38e-06 |  -11.9 | 1.53e-04 |   -0.49    |           |
| v15 (Col5)      | 1475 |     2 cm |  0 cm |       None       | 5.07e-04 | 8.52e-08  | 5.12e-07 | 6.68e-07 |  -12.1 | 1.04e-04 |   -11.9    |           |
| v16 (150 degr.) | 1476 |     2 cm |  0 cm |       None       | 3.76e-04 | 8.52e-07  | 4.09e-07 | 4.46e-07 |  -11.8 | 3.79e-04 |   -0.49    |           |
| v17 (300 degr.) | 1477 |     2 cm |  0 cm |       None       | 4.33e-04 | 1.28e-07  | 4.56e-07 | 4.90e-07 |  -11.3 | 3.72e-04 |   -0.46    |           |
| v18 (Col5)      | 1478 |     2 cm |  0 cm |      25 mm       | 4.95e-04 | 1.24e-07  | 5.16e-07 | 5.53e-07 |  -12.5 | 1.20e-04 |   -0.49    |           |
| v19             | 1479 |     2 cm |  0 cm | 25 mm, 3 mm fill | 1.18e-03 | 5.41e-06  | 1.27e-06 | 1.41e-06 |  -16.7 | 2.20e-04 |   -5.00    |           |
| v20 (Col5)      | 1480 |     2 cm |  0 cm | 25 mm, 3 mm fill | 4.71e-04 | 2.28e-06  | 5.04e-07 | 5.76e-07 |   -8.8 | 1.81e-04 |            |           |
| v21 (Col5)      | 1481 |     2 cm |  0 cm | 50 mm, 3 mm fill | 4.55e-04 | 4.00e-06  | 4.96e-07 | 5.45e-07 |   -7.7 | 2.01e-04 |            |           |
| v22             | 1482 |     2 cm |  0 cm |      75 mm       | 5.12e-04 |     0     | 5.16e-07 | 4.76e-07 |  -16.1 | 3.42e-04 |   -0.47    |           |
| v23             | 1483 |     2 cm |  0 cm |      100 mm      | 5.12e-04 | 1.28e-07  | 5.36e-07 | 5.34e-07 |  -12.4 | 4.52e-04 |   -0.46    |   3.21    |
| v24             | 1484 |     2 cm |  0 cm |      125 mm      | 5.10e-04 |     0     | 5.29e-07 | 5.31e-07 |  -13.5 | 3.77e-04 |   -0.46    |   3.38    |
|-----------------+------+----------+-------+------------------+----------+-----------+----------+----------+--------+----------+------------+-----------|
| <l>             |  <r> |      <r> |   <r> |       <c>        |   <c>    |    <c>    |   <c>    |   <c>    |    <r> |   <c>    |    <c>     |    <c>    |
|-----------------+------+----------+-------+------------------+----------+-----------+----------+----------+--------+----------+------------+-----------|

* Work notes

** Test runs

*** Previous test for config_v03 with mubeam, mustop, mustop_pileup, and edep stages, new elebeam:
$> scripts/run_configuration.py config_v03 --stage summary --mubeam-run-dir runs/config_v03/mubeam_20260406_142342/ --mustop-run-dir runs/config_v03/mustop_20260406_144229/ --mustop-pileup-run-dir runs/config_v03/mustop_pileup_20260407_092828/ --elebeam-run-dir runs/config_v03/elebeam_20260407_135310/
mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/mubeam_20260406_142342
elebeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/elebeam_20260407_135310
mustop: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/mustop_20260406_144229
mustop_pileup: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/mustop_pileup_20260407_092828
final: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/final_20260407_154941
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00097925299
  Calorimeter absolute muon stopping rate: 1.2296858e-05
  mubeam flash output absolute efficiency: 5.9765373e-05
  mubeam average Edep / event: 4.00153 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 4.4074759e-08
  mubeam effective N(POT) simulated: 22688723
  elebeam flash output absolute efficiency: 1.178229e-05
  elebeam average Edep / event: 15.2674 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 5.7474585e-07
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 51706297
  ce: abs eff (all)=1.4785433e-06, abs eff (Edep>50)=1.1961793e-06, MPV=-7.91 MeV, FWHM=7.78 MeV
  ce_plus: abs eff (all)=1.4185893e-06, abs eff (Edep>50)=1.1299397e-06, MPV=-6.52 MeV, FWHM=7.67 MeV
  flat_gamma: abs eff (all)=1.2222883e-06, abs eff (Edep>50)=1.0366242e-06, MPV=-1.91 MeV, FWHM=6.6 MeV
  mustop_pileup effective N(POT) simulated: 3.1023778e+09
  pileup: abs eff (all)=6.7886638e-06, abs eff (Edep>50)=1.2893336e-09, avg Edep/event=3.71499 MeV, effective N(POT) simulated=3.1023778e+09
  Double-Edep expected/event (single,double,triple): 82.6304, 0.00895082, 8.01171e-05
  Double-Edep estimated/event E(50,70,80,90): 4.66855, 0.279876, 0.000629953, 0.000216635
  Rough sensitivity ce: MPV=96.5, FWHM=7, signal rate=46.9788, background rate=1420170, s/sqrt(b)=0.0394214
  Rough sensitivity ce_plus: MPV=85.5, FWHM=6, signal rate=43.5185, background rate=4477620, s/sqrt(b)=0.020566
  Rough sensitivity flat_gamma: MPV=71.5, FWHM=15, signal rate=34198.8, background rate=12399700, s/sqrt(b)=9.71189

*** Submitted a test for config_v06 with mubeam, elebeam, mustop, mustop_pileup, and edep stages:
$> scripts/run_configuration.py config_v06 --stage summary --mubeam-run-dir runs/config_v06/mubeam_20260407_112229/ --mustop-run-dir runs/config_v06/mustop_20260407_114919/ --mustop-pileup-run-dir runs/config_v06/mustop_pileup_20260407_115524/ --elebeam-run-dir runs/config_v06/elebeam_20260407_133433/
mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/mubeam_20260407_112229
elebeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/elebeam_20260407_133433
mustop: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/mustop_20260407_114919
mustop_pileup: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/mustop_pileup_20260407_115524
final: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/final_20260407_155018
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.0012930288
  Calorimeter absolute muon stopping rate: 0
  mubeam flash output absolute efficiency: 1.4485904e-05
  mubeam average Edep / event: 1.64015 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 1.1735547e+08
  elebeam flash output absolute efficiency: 2.0116105e-06
  elebeam average Edep / event: 2.54007 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 39202120
  ce: abs eff (all)=1.7945458e-06, abs eff (Edep>50)=9.0556328e-07, MPV=-50 MeV, FWHM=51.41 MeV
  ce_plus: abs eff (all)=1.5962147e-06, abs eff (Edep>50)=6.5175047e-07, MPV=-44.29 MeV, FWHM=43.22 MeV
  flat_gamma: abs eff (all)=1.5471102e-06, abs eff (Edep>50)=1.1625647e-06, MPV=-2.02 MeV, FWHM=6.91 MeV
  mustop_pileup effective N(POT) simulated: 2.3521272e+09
  pileup: abs eff (all)=4.734863e-06, abs eff (Edep>50)=1.2754412e-09, avg Edep/event=2.21839 MeV, effective N(POT) simulated=2.3521272e+09
  Double-Edep expected/event (single,double,triple): 1.99713, 0.000216336, 4.68012e-08
  Double-Edep estimated/event E(50,70,80,90): 0.00807555, 1.8872e-06, 8.34989e-07, 1.52248e-07
  Rough sensitivity ce: MPV=70.5, FWHM=55, signal rate=87.5957, background rate=7.96275e+09, s/sqrt(b)=0.000981638
  Rough sensitivity ce_plus: MPV=54.5, FWHM=43, signal rate=60.8526, background rate=6.60037e+09, s/sqrt(b)=0.000749023
  Rough sensitivity flat_gamma: MPV=72.5, FWHM=15, signal rate=31052.8, background rate=19869.4, s/sqrt(b)=220.297

*** Higher stats config_v06 submission
$> time python scripts/run_configuration.py config_v06 30 --stage all --events-per-job 150000 --mustop-pileup-events-per-job 500000 --elebeam-events-per-job 50000
Running stage sequence: mubeam -> elebeam -> mustop -> mustop_pileup -> final
FCL: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/config_v06/run1b_beam/mubeam.fcl
Run directory: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/mubeam_20260407_171203

Results:
mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/mubeam_20260407_171203
elebeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/elebeam_20260407_182649
mustop: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/mustop_20260407_191227
run1a_mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/run1a_mubeam_20260408_113504
run1a_mustops: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/run1a_mustops_20260408_115343
mustop_pileup: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/mustop_pileup_20260407_191722
final: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v06/final_20260407_194215
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.0012949404
  Calorimeter absolute muon stopping rate: 0
  mubeam flash output absolute efficiency: 1.4468862e-05
  mubeam average Edep / event: 1.62345 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 3.520664e+08
  elebeam flash output absolute efficiency: 3.9465881e-06
  elebeam average Edep / event: 5.32899 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 52196984
  mustop effective N(POT) simulated (per mode): 38906663
  ce: abs eff (all)=1.7522705e-06, abs eff (Edep>50)=9.072996e-07, MPV=-50 MeV, FWHM=52.31 MeV
  ce_plus: abs eff (all)=1.6578137e-06, abs eff (Edep>50)=6.7854701e-07, MPV=-44.31 MeV, FWHM=42.65 MeV
  flat_gamma: abs eff (all)=1.5877743e-06, abs eff (Edep>50)=1.1919552e-06, MPV=-1.64 MeV, FWHM=6.27 MeV
  run1a target absolute muon stopping rate: 0.0021241337
  run1a_mustops effective N(POT) simulated (per mode): 23605540
  run1a ce: eff/mu stop (all)=0.00456, eff/mu stop (Edep>50)=0.00166, abs eff (all)=9.6587495e-06, abs eff (Edep>50)=3.5161237e-06, MPV=-50 MeV, FWHM=47.23 MeV, trk-front MPV=-53.9 MeV, FWHM=21 MeV, eff=0.807
  run1a ce_plus: eff/mu stop (all)=0.00102, eff/mu stop (Edep>50)=0.00034, abs eff (all)=2.1605098e-06, abs eff (Edep>50)=7.2016992e-07, MPV=unavailable MeV, FWHM=unavailable MeV, trk-front MPV=-39.1 MeV, FWHM=12.2 MeV, eff=0.7451
  run1a flat_gamma: eff/mu stop (all)=0.00136, eff/mu stop (Edep>50)=0.0008, abs eff (all)=7.2016992e-08, abs eff (Edep>50)=4.2362936e-08, MPV=unavailable MeV, FWHM=unavailable MeV, trk-front MPV=-0.1 MeV, FWHM=0 MeV, eff=0.6324
  mustop_pileup effective N(POT) simulated: 1.1671999e+10
  pileup: abs eff (all)=4.7476015e-06, abs eff (Edep>50)=6.8540102e-10, avg Edep/event=2.14676 MeV, effective N(POT) simulated=1.1671999e+10
  Double-Edep expected/event (single,double,triple): 72.4016, 0.3002, 0.0008
  Double-Edep estimated/event E(50,70,80,90): 0.00373444, 0.000541468, 0.000246479, 1.00796e-05
  Rough sensitivity ce: MPV=69.5, FWHM=54, signal rate=617.802, background rate=1.30601e+11, s/sqrt(b)=0.00170953
  Rough sensitivity ce_plus: MPV=54.5, FWHM=43, signal rate=460.907, background rate=1.15152e+11, s/sqrt(b)=0.00135824
  Rough sensitivity flat_gamma: MPV=71.5, FWHM=15, signal rate=237214, background rate=44120000, s/sqrt(b)=35.7127

*** Higher stats config_v03 submission, included test run1a evaluation
$> time python scripts/run_configuration.py config_v03 30 --stage all --events-per-job 150000 --mustop-pileup-events-per-job 500000 --elebeam-events-per-job 50000
Running stage sequence: mubeam -> elebeam -> mustop -> mustop_pileup -> final
FCL: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/config_v03/run1b_beam/mubeam.fcl
Run directory: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/mubeam_20260407_194920

$> scripts/run_configuration.py config_v03 --stage summary --mubeam-run-dir runs/config_v03/mubeam_20260407_194920/ --mustop-run-dir runs/config_v03/mustop_20260407_215515/ --mustop-pileup-run-dir runs/config_v03/mustop_pileup_20260407_220010/ --elebeam-run-dir runs/config_v03/elebeam_20260407_210757/
mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/mubeam_20260407_194920
elebeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/elebeam_20260407_210757
mustop: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/mustop_20260407_215515
run1a_mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/run1a_mubeam_20260408_093647
run1a_mustops: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/run1a_mustops_20260408_094501
mustop_pileup: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/mustop_pileup_20260407_220010
final: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v03/final_20260407_222736
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00096218783
  Calorimeter absolute muon stopping rate: 1.2435154e-05
  mubeam flash output absolute efficiency: 6.131798e-05
  mubeam average Edep / event: 4.1072 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 9.373232e-08
  mubeam effective N(POT) simulated: 3.520664e+08
  elebeam flash output absolute efficiency: 9.6940466e-06
  elebeam average Edep / event: 10.4077 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 9.5790974e-08
  elebeam effective N(POT) simulated: 52196984
  mustop effective N(POT) simulated (per mode): 52240021
  ce: abs eff (all)=1.436638e-06, abs eff (Edep>50)=1.1791726e-06, MPV=-7.64 MeV, FWHM=7.63 MeV
  ce_plus: abs eff (all)=1.4146242e-06, abs eff (Edep>50)=1.1389735e-06, MPV=-6.37 MeV, FWHM=6.89 MeV
  flat_gamma: abs eff (all)=1.2045363e-06, abs eff (Edep>50)=1.0217262e-06, MPV=-1.86 MeV, FWHM=6.1 MeV
  run1a target absolute muon stopping rate: 0.0016740082
  run1a_mustops effective N(POT) simulated (per mode): 29971793
  run1a ce: eff/mu stop (all)=0.17472, eff/mu stop (Edep>50)=0.14118, abs eff (all)=0.00029147405, abs eff (Edep>50)=0.00023552144, MPV=-12.78 MeV, FWHM=15.16 MeV
  run1a ce_plus: eff/mu stop (all)=0.12698, eff/mu stop (Edep>50)=0.10262, abs eff (all)=0.00021183251, abs eff (Edep>50)=0.0001711943, MPV=-10.95 MeV, FWHM=14.07 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00136, eff/mu stop (Edep>50)=0.00064, abs eff (all)=2.2687999e-06, abs eff (Edep>50)=1.0676705e-06, MPV=unavailable MeV, FWHM=unavailable MeV
  mustop_pileup effective N(POT) simulated: 1.5672006e+10
  pileup: abs eff (all)=6.7565696e-06, abs eff (Edep>50)=1.531393e-09, avg Edep/event=3.64687 MeV, effective N(POT) simulated=1.5672006e+10
  Double-Edep expected/event (single,double,triple): 225.82, 2.8003, 0.0192
  Double-Edep estimated/event E(50,70,80,90): 1.48527, 0.0899742, 0.0117728, 0.00291701
  Rough sensitivity ce: MPV=98.5, FWHM=6, signal rate=308.549, background rate=1.39929e+08, s/sqrt(b)=0.0260838
  Rough sensitivity ce_plus: MPV=86.5, FWHM=6, signal rate=322.088, background rate=6.09469e+08, s/sqrt(b)=0.0130466
  Rough sensitivity flat_gamma: MPV=73.5, FWHM=15, signal rate=243461, background rate=3.6951e+09, s/sqrt(b)=4.00512
 
*** Low stats config_v10: 2 cm Al, 5 cm poly
>time python scripts/run_configuration.py config_v10 10 --stage all --events-per-job 10000 --mustop-pileup-events-per-job 50000 --elebeam-events-per-job 10000
Running stage sequence: mubeam -> elebeam -> mustop -> run1a_mubeam -> run1a_mustops -> mustop_pileup -> final

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v10/mubeam_20260408_142616
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v10/elebeam_20260408_143234
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v10/run1a_mubeam_20260408_144049
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v10/run1a_mustops_20260408_144509
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v10/mustop_20260408_143545
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v10/mustop_pileup_20260408_145022
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v10/final_20260408_145240
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.0012912053
  Calorimeter absolute muon stopping rate: 0
  mubeam flash output absolute efficiency: 1.878907e-05
  mubeam average Edep / event: 1.43003 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 7823697.7
  elebeam flash output absolute efficiency: 2.5863563e-06
  elebeam average Edep / event: 6.835 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 1159933
  mustop effective N(POT) simulated (per mode): 37722747
  ce: abs eff (all)=2.0299423e-06, abs eff (Edep>50)=1.2651518e-06, MPV=-41.85 MeV, FWHM=60.03 MeV
  ce_plus: abs eff (all)=1.8934199e-06, abs eff (Edep>50)=1.0457881e-06, MPV=-34.59 MeV, FWHM=42.2 MeV
  flat_gamma: abs eff (all)=1.7224356e-06, abs eff (Edep>50)=1.3307621e-06, MPV=-1.25 MeV, FWHM=6.47 MeV
  run1a target absolute muon stopping rate: 0.0021237916
  run1a_mustops effective N(POT) simulated (per mode): 23609353
  run1a ce: eff/mu stop (all)=0.01728, eff/mu stop (Edep>50)=0.01128, abs eff (all)=3.6595666e-05, abs eff (Edep>50)=2.3888837e-05, MPV=-38.34 MeV, FWHM=27.12 MeV, trk-front MPV=-42.5 MeV, FWHM=26.6 MeV, eff=0.8762
  run1a ce_plus: eff/mu stop (all)=0.00718, eff/mu stop (Edep>50)=0.00378, abs eff (all)=1.5205838e-05, abs eff (Edep>50)=8.0053018e-06, MPV=-34.02 MeV, FWHM=24.72 MeV, trk-front MPV=-26.3 MeV, FWHM=10.6 MeV, eff=0.8384
  run1a flat_gamma: eff/mu stop (all)=0.00104, eff/mu stop (Edep>50)=0.00042, abs eff (all)=5.5062923e-08, abs eff (Edep>50)=2.223695e-08, MPV=unavailable MeV, FWHM=unavailable MeV, trk-front MPV=-0.1 MeV, FWHM=0 MeV, eff=0.5
  mustop_pileup effective N(POT) simulated: 3.7722747e+08
  pileup: abs eff (all)=6.5769336e-06, abs eff (Edep>50)=0, avg Edep/event=2.46926 MeV, effective N(POT) simulated=3.7722747e+08
  Double-Edep expected/event (single,double,triple): 68.4861, 0.2699, 0.0005
  Double-Edep estimated/event E(50,70,80,90): 0.000271829, 6.52571e-07, 5.08052e-08, 2.30261e-10
  Rough sensitivity ce: MPV=81.5, FWHM=61, signal rate=835.669, background rate=6.75253e+10, s/sqrt(b)=0.00321589
  Rough sensitivity ce_plus: MPV=67.5, FWHM=48, signal rate=671.003, background rate=5.95027e+10, s/sqrt(b)=0.00275078
  Rough sensitivity flat_gamma: MPV=71.5, FWHM=15, signal rate=285712, background rate=22338.9, s/sqrt(b)=1911.6

*** Medium stats config_v12
$> time python scripts/run_configuration.py config_v12 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 100000 --events-per-job 30000 --elebeam-events-per-job 30000 --run1a-mubeam-events-per-job 5000
real    59m25.946s
user    1318m45.128s
sys     29m37.612s

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v12/mubeam_20260410_083903
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v12/elebeam_20260410_085644
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v12/run1a_mubeam_20260410_091608
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v12/run1a_mustops_20260410_092152
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v12/mustop_20260410_090753
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v12/mustop_pileup_20260410_093145
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v12/final_20260410_093813
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.0012980364
  Calorimeter absolute muon stopping rate: 6.816896e-07
  mubeam flash output absolute efficiency: 2.1842471e-05
  mubeam average Edep / event: 2.30846 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 70413279
  elebeam flash output absolute efficiency: 7.375905e-06
  elebeam average Edep / event: 8.87009 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 10439397
  mustop effective N(POT) simulated (per mode): 77977053
  ce: abs eff (all)=2.0166189e-06, abs eff (Edep>50)=1.4369612e-06, MPV=-11.1 MeV, FWHM=8.381 MeV
  ce_plus: abs eff (all)=2.0076419e-06, abs eff (Edep>50)=1.3786107e-06, MPV=-10.54 MeV, FWHM=7.311 MeV
  flat_gamma: abs eff (all)=1.6479207e-06, abs eff (Edep>50)=1.3125656e-06, MPV=-1.85 MeV, FWHM=5.308 MeV
  run1a target absolute muon stopping rate: 0.0025153465
  run1a_mustops effective N(POT) simulated (per mode): 41348453
  run1a ce: eff/mu stop (all)=0.06231, eff/mu stop (Edep>50)=0.04258, abs eff (all)=0.00015069488, abs eff (Edep>50)=0.00010297846, MPV=-16.68 MeV, FWHM=23.6 MeV, trk-front fit MPV=-10.83 MeV, FWHM=23.06 MeV
  run1a ce_plus: eff/mu stop (all)=0.03325, eff/mu stop (Edep>50)=0.02019, abs eff (all)=8.0414133e-05, abs eff (Edep>50)=4.8828912e-05, MPV=-13.3 MeV, FWHM=20.3 MeV, trk-front fit MPV=-8.75 MeV, FWHM=19.57 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00129675, eff/mu stop (Edep>50)=0.001007, abs eff (all)=3.1361512e-06, abs eff (Edep>50)=2.4353994e-06, MPV=-1.65 MeV, FWHM=5.001 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0.09 MeV
  mustop_pileup effective N(POT) simulated: 2.3393116e+09
  pileup: abs eff (all)=8.0622009e-06, abs eff (Edep>50)=1.2824286e-09, avg Edep/event=3.07399 MeV, effective N(POT) simulated=2.3393116e+09
  Double-Edep expected/event (single,double,triple): 125.601, 0.8709, 0.003
  Double-Edep estimated/event E(50,70,80,90): 0.0737645, 0.00279902, 0.000774307, 6.54469e-05
  Rough sensitivity ce: MPV=90.5, FWHM=12, signal rate=348.544, background rate=64966200, s/sqrt(b)=0.0432428
  Rough sensitivity ce_plus: MPV=79.5, FWHM=12, signal rate=380.903, background rate=2.28384e+08, s/sqrt(b)=0.0252047
  Rough sensitivity flat_gamma: MPV=76.5, FWHM=15, signal rate=286640, background rate=1.67348e+08, s/sqrt(b)=22.1578

*** Low stats config_v13
time python scripts/run_configuration.py config_v13 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v13/mubeam_20260410_103122
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v13/elebeam_20260410_103932
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v13/run1a_mubeam_20260410_105337
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v13/run1a_mustops_20260410_105943
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v13/mustop_20260410_104432
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v13/mustop_pileup_20260410_110936
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v13/final_20260410_111334
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.0011924029
  Calorimeter absolute muon stopping rate: 1.491196e-06
  mubeam flash output absolute efficiency: 2.7523218e-05
  mubeam average Edep / event: 2.59832 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 1.0920171e-05
  elebeam average Edep / event: 10.5867 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 85660923
  ce: abs eff (all)=1.8348506e-06, abs eff (Edep>50)=1.4070009e-06, MPV=-9.95 MeV, FWHM=7.163 MeV
  ce_plus: abs eff (all)=1.7519657e-06, abs eff (Edep>50)=1.2911371e-06, MPV=-8.33 MeV, FWHM=7.305 MeV
  flat_gamma: abs eff (all)=1.5009761e-06, abs eff (Edep>50)=1.249111e-06, MPV=-1.65 MeV, FWHM=6.2 MeV
  run1a target absolute muon stopping rate: 0.0022999091
  run1a_mustops effective N(POT) simulated (per mode): 45241721
  run1a ce: eff/mu stop (all)=0.09357, eff/mu stop (Edep>50)=0.065, abs eff (all)=0.00020682237, abs eff (Edep>50)=0.00014367269, MPV=-15.51 MeV, FWHM=15.66 MeV, trk-front fit MPV=-9.66 MeV, FWHM=13.96 MeV
  run1a ce_plus: eff/mu stop (all)=0.05401, eff/mu stop (Edep>50)=0.03275, abs eff (all)=0.00011938096, abs eff (Edep>50)=7.2388934e-05, MPV=-13.3 MeV, FWHM=13.91 MeV, trk-front fit MPV=-9.15 MeV, FWHM=13.32 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00134525, eff/mu stop (Edep>50)=0.001038, abs eff (all)=2.9734722e-06, abs eff (Edep>50)=2.2943424e-06, MPV=-0.65 MeV, FWHM=5.8 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0 MeV
  mustop_pileup effective N(POT) simulated: 1.2849139e+09
  pileup: abs eff (all)=7.4409658e-06, abs eff (Edep>50)=7.7826229e-10, avg Edep/event=3.19833 MeV, effective N(POT) simulated=1.2849139e+09
  Double-Edep expected/event (single,double,triple): 148.125, 1.207, 0.0051
  Double-Edep estimated/event E(50,70,80,90): 0.147132, 0.0108125, 0.00183523, 0.000156
  Rough sensitivity ce: MPV=93.5, FWHM=9, signal rate=365.449, background rate=51890100, s/sqrt(b)=0.0507322
  Rough sensitivity ce_plus: MPV=81.5, FWHM=10, signal rate=372.126, background rate=6.91665e+08, s/sqrt(b)=0.0141495
  Rough sensitivity flat_gamma: MPV=85.5, FWHM=15, signal rate=298155, background rate=6.10293e+08, s/sqrt(b)=12.069

real    42m30.586s
user    827m32.109s
sys     27m46.564s

*** Low stats config_v14
time python scripts/run_configuration.py config_v14 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v14/mubeam_20260410_094606
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v14/elebeam_20260410_095351
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v14/run1a_mubeam_20260410_100742
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v14/run1a_mustops_20260410_101319
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v14/mustop_20260410_095850
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v14/mustop_pileup_20260410_102403
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v14/final_20260410_102757
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.0012831955
  Calorimeter absolute muon stopping rate: 1.6616184e-06
  mubeam flash output absolute efficiency: 2.2708785e-05
  mubeam average Edep / event: 2.31972 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 4.26056e-08
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 7.1843231e-06
  elebeam average Edep / event: 7.94664 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 79133827
  ce: abs eff (all)=2.0282098e-06, abs eff (Edep>50)=1.3783612e-06, MPV=-11.86 MeV, FWHM=9.27 MeV
  ce_plus: abs eff (all)=1.9606028e-06, abs eff (Edep>50)=1.2459905e-06, MPV=-11.28 MeV, FWHM=10.65 MeV
  flat_gamma: abs eff (all)=1.6772221e-06, abs eff (Edep>50)=1.3372916e-06, MPV=-3.45 MeV, FWHM=5.9 MeV
  run1a target absolute muon stopping rate: 0.00241133
  run1a_mustops effective N(POT) simulated (per mode): 43160712
  run1a ce: eff/mu stop (all)=0.08963, eff/mu stop (Edep>50)=0.06619, abs eff (all)=0.00020766571, abs eff (Edep>50)=0.00015335706, MPV=-7.64 MeV, FWHM=9.124 MeV, trk-front fit MPV=-0.49 MeV, FWHM=0.66 MeV
  run1a ce_plus: eff/mu stop (all)=0.05661, eff/mu stop (Edep>50)=0.03905, abs eff (all)=0.00013116095, abs eff (Edep>50)=9.0475801e-05, MPV=-5.35 MeV, FWHM=7.043 MeV, trk-front fit MPV=-0.6 MeV, FWHM=0.78 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00151675, eff/mu stop (Edep>50)=0.00103225, abs eff (all)=3.5141913e-06, abs eff (Edep>50)=2.3916426e-06, MPV=-1.95 MeV, FWHM=4.9 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0.07 MeV
  mustop_pileup effective N(POT) simulated: 1.1870074e+09
  pileup: abs eff (all)=8.3125008e-06, abs eff (Edep>50)=0, avg Edep/event=2.98528 MeV, effective N(POT) simulated=1.1870074e+09
  Double-Edep expected/event (single,double,triple): 114.474, 0.727, 0.0019
  Double-Edep estimated/event E(50,70,80,90): 0.0713161, 0.0012867, 0.000183063, 1.64715e-05
  Rough sensitivity ce: MPV=89.5, FWHM=17, signal rate=389.239, background rate=38674500, s/sqrt(b)=0.0625899
  Rough sensitivity ce_plus: MPV=78.5, FWHM=10, signal rate=276.102, background rate=94334700, s/sqrt(b)=0.0284271
  Rough sensitivity flat_gamma: MPV=74.5, FWHM=15, signal rate=286552, background rate=58181100, s/sqrt(b)=37.5675

real    42m9.606s
user    847m4.176s
sys     26m40.538s

*** Low stats config_15 (2 cm Al, no poly, Col5 added)
time python scripts/run_configuration.py config_v15 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v15/mubeam_20260410_125257
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v15/elebeam_20260410_130033
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v15/run1a_mubeam_20260410_131411
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v15/run1a_mustops_20260410_131959
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v15/mustop_20260410_130529
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v15/mustop_pileup_20260410_132918
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v15/final_20260410_133308
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00050700664
  Calorimeter absolute muon stopping rate: 8.52112e-08
  mubeam flash output absolute efficiency: 1.0012316e-05
  mubeam average Edep / event: 1.97528 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 4.8853397e-06
  elebeam average Edep / event: 9.04997 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 2.002653e+08
  ce: abs eff (all)=7.6897995e-07, abs eff (Edep>50)=5.6787172e-07, MPV=-12.07 MeV, FWHM=8.632 MeV
  ce_plus: abs eff (all)=7.5399982e-07, abs eff (Edep>50)=5.1207074e-07, MPV=-10.41 MeV, FWHM=7.332 MeV
  flat_gamma: abs eff (all)=6.5463164e-07, abs eff (Edep>50)=5.2854888e-07, MPV=-1.85 MeV, FWHM=4.703 MeV
  run1a target absolute muon stopping rate: 0.0021056275
  run1a_mustops effective N(POT) simulated (per mode): 49239818
  run1a ce: eff/mu stop (all)=0.05145, eff/mu stop (Edep>50)=0.03465, abs eff (all)=0.00010448861, abs eff (Edep>50)=7.0369879e-05, MPV=-16.43 MeV, FWHM=23.36 MeV, trk-front fit MPV=-11.88 MeV, FWHM=22.02 MeV
  run1a ce_plus: eff/mu stop (all)=0.02636, eff/mu stop (Edep>50)=0.01456, abs eff (all)=5.3533911e-05, abs eff (Edep>50)=2.9569565e-05, MPV=-14.62 MeV, FWHM=20.34 MeV, trk-front fit MPV=-11.27 MeV, FWHM=17.04 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00129275, eff/mu stop (Edep>50)=0.00100225, abs eff (all)=2.6254159e-06, abs eff (Edep>50)=2.0354462e-06, MPV=-1.25 MeV, FWHM=6.8 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0 MeV
  mustop_pileup effective N(POT) simulated: 3.0039795e+09
  pileup: abs eff (all)=3.3215939e-06, abs eff (Edep>50)=3.3289175e-10, avg Edep/event=3.03772 MeV, effective N(POT) simulated=3.0039795e+09
  Double-Edep expected/event (single,double,triple): 59.5729, 0.2069, 0.0003
  Double-Edep estimated/event E(50,70,80,90): 0.0314677, 0.000946382, 0.000266344, 2.49832e-05
  Rough sensitivity ce: MPV=90.5, FWHM=17, signal rate=182.265, background rate=46154600, s/sqrt(b)=0.0268284
  Rough sensitivity ce_plus: MPV=80.5, FWHM=12, signal rate=140.457, background rate=89803400, s/sqrt(b)=0.0148216
  Rough sensitivity flat_gamma: MPV=72.5, FWHM=15, signal rate=114950, background rate=57626500, s/sqrt(b)=15.1425

real    40m29.352s
user    798m56.685s
sys     27m2.820s

*** Low stats config_v16 (degrader, 2 cm)
time python scripts/run_configuration.py config_v16 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000
--> Had to restart with fixed Run 1A geom with degrader moved, lowered the run1a_mustops stats

mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v16/mubeam_20260410_112336
elebeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v16/elebeam_20260410_113111
mustop: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v16/mustop_20260410_113609
run1a_mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v16/run1a_mubeam_20260410_122034
run1a_mustops: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v16/run1a_mustops_20260410_124435
mustop_pileup: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v16/mustop_pileup_20260410_120028
final: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v16/final_20260410_120425
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.000375824
  Calorimeter absolute muon stopping rate: 8.52112e-07
  mubeam flash output absolute efficiency: 2.0067238e-05
  mubeam average Edep / event: 2.98807 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 4.3105939e-06
  elebeam average Edep / event: 8.35151 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 2.6137075e+08
  ce: abs eff (all)=6.4180863e-07, abs eff (Edep>50)=4.463009e-07, MPV=-11.83 MeV, FWHM=8.448 MeV
  ce_plus: abs eff (all)=6.0603569e-07, abs eff (Edep>50)=3.9273714e-07, MPV=-11.6 MeV, FWHM=8.7 MeV
  flat_gamma: abs eff (all)=5.1535989e-07, abs eff (Edep>50)=4.0928452e-07, MPV=-2.95 MeV, FWHM=6.2 MeV
  run1a target absolute muon stopping rate: 0.0007857648
  run1a_mustops effective N(POT) simulated (per mode): 13211088
  run1a ce: eff/mu stop (all)=0.5764, eff/mu stop (Edep>50)=0.5001, abs eff (all)=0.00043630016, abs eff (Edep>50)=0.00037854565, MPV=-13.91 MeV, FWHM=5.7 MeV, trk-front fit MPV=-7.26 MeV, FWHM=0 MeV
  run1a ce_plus: eff/mu stop (all)=0.4924, eff/mu stop (Edep>50)=0.4028, abs eff (all)=0.00037271721, abs eff (Edep>50)=0.00030489539, MPV=-6.18 MeV, FWHM=5.146 MeV, trk-front fit MPV=-0.53 MeV, FWHM=0.69 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00232, eff/mu stop (Edep>50)=0.0018125, abs eff (all)=1.7561006e-06, abs eff (Edep>50)=1.3719536e-06, MPV=-1.55 MeV, FWHM=6.3 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0 MeV
  mustop_pileup effective N(POT) simulated: 3.9205612e+09
  pileup: abs eff (all)=2.7240998e-06, abs eff (Edep>50)=7.6519658e-10, avg Edep/event=2.94651 MeV, effective N(POT) simulated=3.9205612e+09
  Double-Edep expected/event (single,double,triple): 62.0201, 0.2225, 0.0004
  Double-Edep estimated/event E(50,70,80,90): 0.0131101, 0.000422524, 2.38097e-05, 3.02577e-06
  Rough sensitivity ce: MPV=90.5, FWHM=15, signal rate=125.374, background rate=4762620, s/sqrt(b)=0.0574493
  Rough sensitivity ce_plus: MPV=78.5, FWHM=13, signal rate=107.199, background rate=59596900, s/sqrt(b)=0.0138861
  Rough sensitivity flat_gamma: MPV=74.5, FWHM=15, signal rate=91938.6, background rate=12406400, s/sqrt(b)=26.1021

*** Low stats config_v17 (big degrader)
time python scripts/run_configuration.py config_v17 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v17/mubeam_20260410_140206
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v17/elebeam_20260410_140940
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v17/run1a_mubeam_20260410_142332
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v17/run1a_mustops_20260410_142909
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v17/mustop_20260410_141438
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v17/mustop_pileup_20260410_144734
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v17/final_20260410_145130
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00043300071
  Calorimeter absolute muon stopping rate: 1.278168e-07
  mubeam flash output absolute efficiency: 1.2952102e-05
  mubeam average Edep / event: 1.88583 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 5.1727126e-06
  elebeam average Edep / event: 8.08977 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 2.3424245e+08
  ce: abs eff (all)=6.9287187e-07, abs eff (Edep>50)=4.9019724e-07, MPV=-11.3 MeV, FWHM=8.859 MeV
  ce_plus: abs eff (all)=6.8646824e-07, abs eff (Edep>50)=4.4643916e-07, MPV=-12.14 MeV, FWHM=8.506 MeV
  flat_gamma: abs eff (all)=5.7408468e-07, abs eff (Edep>50)=4.5561768e-07, MPV=-0.65 MeV, FWHM=5.8 MeV
  run1a target absolute muon stopping rate: 0.00078444255
  run1a_mustops effective N(POT) simulated (per mode): 1.3226491e+08
  run1a ce: eff/mu stop (all)=0.57255, eff/mu stop (Edep>50)=0.49246, abs eff (all)=0.00043288124, abs eff (Edep>50)=0.00037232852, MPV=-7.01 MeV, FWHM=6.731 MeV, trk-front fit MPV=-0.46 MeV, FWHM=0.65 MeV
  run1a ce_plus: eff/mu stop (all)=0.49785, eff/mu stop (Edep>50)=0.40638, abs eff (all)=0.00037640368, abs eff (Edep>50)=0.00030724702, MPV=-5.49 MeV, FWHM=6.539 MeV, trk-front fit MPV=-0.54 MeV, FWHM=0.71 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00231725, eff/mu stop (Edep>50)=0.001822, abs eff (all)=1.7519763e-06, abs eff (Edep>50)=1.3775384e-06, MPV=-1.15 MeV, FWHM=5.3 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0 MeV
  mustop_pileup effective N(POT) simulated: 3.5136367e+09
  pileup: abs eff (all)=3.0210864e-06, abs eff (Edep>50)=5.6921082e-10, avg Edep/event=3.04672 MeV, effective N(POT) simulated=3.5136367e+09
  Double-Edep expected/event (single,double,triple): 57.9366, 0.1951, 0.0006
  Double-Edep estimated/event E(50,70,80,90): 0.00356234, 0.000261083, 5.18428e-06, 5.67875e-07
  Rough sensitivity ce: MPV=88.5, FWHM=13, signal rate=128.031, background rate=560268, s/sqrt(b)=0.171048
  Rough sensitivity ce_plus: MPV=79.5, FWHM=13, signal rate=123.237, background rate=40718800, s/sqrt(b)=0.0193128
  Rough sensitivity flat_gamma: MPV=78.5, FWHM=15, signal rate=100322, background rate=3326850, s/sqrt(b)=55.0023

real    49m43.116s
user    948m9.490s
sys     28m28.803s

*** Low stats config_v18 (hole + col5)
time python scripts/run_configuration.py config_v18 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v18/mubeam_20260410_151339
elebeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v18/elebeam_20260410_152120
mustop: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v18/mustop_20260410_152616
run1a_mubeam: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v18/run1a_mubeam_20260410_153506
run1a_mustops: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v18/run1a_mustops_20260410_154057
mustop_pileup: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v18/mustop_pileup_20260410_155115
final: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v18/final_20260410_155504
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00049507707
  Calorimeter absolute muon stopping rate: 1.2355624e-06
  mubeam flash output absolute efficiency: 1.2866891e-05
  mubeam average Edep / event: 2.39948 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 5.1727126e-06
  elebeam average Edep / event: 7.58563 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 2.0216273e+08
  ce: abs eff (all)=7.9725378e-07, abs eff (Edep>50)=5.531435e-07, MPV=-12.5 MeV, FWHM=9.874 MeV
  ce_plus: abs eff (all)=7.8736075e-07, abs eff (Edep>50)=5.0639898e-07, MPV=-11.08 MeV, FWHM=9.249 MeV
  flat_gamma: abs eff (all)=6.4972411e-07, abs eff (Edep>50)=5.1604467e-07, MPV=-1.95 MeV, FWHM=4.5 MeV
  run1a target absolute muon stopping rate: 0.0020002007
  run1a_mustops effective N(POT) simulated (per mode): 51859939
  run1a ce: eff/mu stop (all)=0.08387, eff/mu stop (Edep>50)=0.06217, abs eff (all)=0.00016172406, abs eff (Edep>50)=0.00011988059, MPV=-5.94 MeV, FWHM=7.232 MeV, trk-front fit MPV=-0.49 MeV, FWHM=0.68 MeV
  run1a ce_plus: eff/mu stop (all)=0.05072, eff/mu stop (Edep>50)=0.03467, abs eff (all)=9.7801889e-05, abs eff (Edep>50)=6.6853145e-05, MPV=-5.26 MeV, FWHM=7.539 MeV, trk-front fit MPV=-0.61 MeV, FWHM=0.77 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00149875, eff/mu stop (Edep>50)=0.001011, abs eff (all)=2.8899957e-06, abs eff (Edep>50)=1.9494817e-06, MPV=-2.45 MeV, FWHM=5.527 MeV, trk-front fit MPV=-0 MeV, FWHM=0.55 MeV
  mustop_pileup effective N(POT) simulated: 3.032441e+09
  pileup: abs eff (all)=3.3520851e-06, abs eff (Edep>50)=3.2976734e-10, avg Edep/event=2.98855 MeV, effective N(POT) simulated=3.032441e+09
  Double-Edep expected/event (single,double,triple): 62.1501, 0.2234, 0.0004
  Double-Edep estimated/event E(50,70,80,90): 0.00426992, 3.93134e-05, 2.26391e-06, 3.26853e-07
  Rough sensitivity ce: MPV=91.5, FWHM=12, signal rate=129.789, background rate=237252, s/sqrt(b)=0.266461
  Rough sensitivity ce_plus: MPV=78.5, FWHM=14, signal rate=140.357, background rate=8410300, s/sqrt(b)=0.0483981
  Rough sensitivity flat_gamma: MPV=76.5, FWHM=15, signal rate=110532, background rate=930724, s/sqrt(b)=114.572

*** Low stats config_v19 (thin Al center in plate)
time python scripts/run_configuration.py config_v19 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v19/mubeam_20260410_161629
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v19/elebeam_20260410_162453
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v19/run1a_mubeam_20260410_163815
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v19/run1a_mustops_20260410_164409
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v19/mustop_20260410_163000
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v19/mustop_pileup_20260410_165509
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v19/final_20260410_165907
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.0011837966
  Calorimeter absolute muon stopping rate: 5.4109112e-06
  mubeam flash output absolute efficiency: 3.5277437e-05
  mubeam average Edep / event: 3.33778 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 8.52112e-08
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 7.7590689e-06
  elebeam average Edep / event: 8.76661 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 84855723
  ce: abs eff (all)=1.7983466e-06, abs eff (Edep>50)=1.4053265e-06, MPV=-16.66 MeV, FWHM=7.3 MeV
  ce_plus: abs eff (all)=1.7889188e-06, abs eff (Edep>50)=1.3458138e-06, MPV=-7.41 MeV, FWHM=8.933 MeV
  flat_gamma: abs eff (all)=1.5331906e-06, abs eff (Edep>50)=1.2686239e-06, MPV=-0.65 MeV, FWHM=5.847 MeV
  run1a target absolute muon stopping rate: 0.0022077928
  run1a_mustops effective N(POT) simulated (per mode): 47162059
  run1a ce: eff/mu stop (all)=0.13647, eff/mu stop (Edep>50)=0.10392, abs eff (all)=0.00028936396, abs eff (Edep>50)=0.00022034661, MPV=-5.55 MeV, FWHM=6.102 MeV, trk-front fit MPV=-0 MeV, FWHM=0.16 MeV
  run1a ce_plus: eff/mu stop (all)=0.08129, eff/mu stop (Edep>50)=0.05796, abs eff (all)=0.00017236313, abs eff (Edep>50)=0.0001228954, MPV=-4.05 MeV, FWHM=8.201 MeV, trk-front fit MPV=-0 MeV, FWHM=0.14 MeV
  run1a flat_gamma: eff/mu stop (all)=0.001345, eff/mu stop (Edep>50)=0.0010505, abs eff (all)=2.8518687e-06, abs eff (Edep>50)=2.2274261e-06, MPV=-1.75 MeV, FWHM=5.7 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0.07 MeV
  mustop_pileup effective N(POT) simulated: 1.2728358e+09
  pileup: abs eff (all)=7.9201101e-06, abs eff (Edep>50)=3.1425891e-09, avg Edep/event=3.40586 MeV, effective N(POT) simulated=1.2728358e+09
  Double-Edep expected/event (single,double,triple): 142.462, 1.1193, 0.0042
  Double-Edep estimated/event E(50,70,80,90): 0.534685, 0.0592751, 0.00191672, 0.000484421
  Rough sensitivity ce: MPV=96.5, FWHM=7, signal rate=334.681, background rate=33397200, s/sqrt(b)=0.057913
  Rough sensitivity ce_plus: MPV=84.5, FWHM=8, signal rate=373.104, background rate=2.65472e+08, s/sqrt(b)=0.0228992
  Rough sensitivity flat_gamma: MPV=74.5, FWHM=15, signal rate=295050, background rate=8.46726e+08, s/sqrt(b)=10.1397

real    42m58.022s
user    834m5.514s
sys     27m6.388s

*** Low stats config_v20 (thin Al center in plate, Col5)
time python scripts/run_configuration.py config_v20 40 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 10000 --events-per-job 8000 --elebeam-events-per-job 5000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v20/mubeam_20260411_084458
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v20/elebeam_20260411_085339
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v20/run1a_mubeam_20260411_090628
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v20/run1a_mustops_20260411_091334
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v20/mustop_20260411_085805
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v20/mustop_pileup_20260411_092405
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v20/final_20260411_092643
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00047076525
  Calorimeter absolute muon stopping rate: 2.2767368e-06
  mubeam flash output absolute efficiency: 1.6935726e-05
  mubeam average Edep / event: 3.76902 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 3.994275e-08
  mubeam effective N(POT) simulated: 25035833
  elebeam flash output absolute efficiency: 5.603772e-06
  elebeam average Edep / event: 8.46279 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 2319866
  mustop effective N(POT) simulated (per mode): 2.1325241e+08
  ce: abs eff (all)=7.3164473e-07, abs eff (Edep>50)=5.7572621e-07, MPV=-8.82 MeV, FWHM=7.893 MeV
  ce_plus: abs eff (all)=7.0456415e-07, abs eff (Edep>50)=5.2742664e-07, MPV=-5.6 MeV, FWHM=7.222 MeV
  flat_gamma: abs eff (all)=6.0632376e-07, abs eff (Edep>50)=5.0374578e-07, MPV=-1.75 MeV, FWHM=5.3 MeV
  run1a target absolute muon stopping rate: 0.001868278
  run1a_mustops effective N(POT) simulated (per mode): 55262372
  run1a ce: eff/mu stop (all)=0.13133, eff/mu stop (Edep>50)=0.10022, abs eff (all)=0.00023764814, abs eff (Edep>50)=0.00018135305, MPV=-5.45 MeV, FWHM=6.402 MeV, trk-front fit MPV=-0 MeV, FWHM=0.17 MeV
  run1a ce_plus: eff/mu stop (all)=0.07515, eff/mu stop (Edep>50)=0.05409, abs eff (all)=0.00013598765, abs eff (Edep>50)=9.7878534e-05, MPV=-4.85 MeV, FWHM=6.502 MeV, trk-front fit MPV=-0 MeV, FWHM=0.15 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00134275, eff/mu stop (Edep>50)=0.00104575, abs eff (all)=2.4297726e-06, abs eff (Edep>50)=1.8923364e-06, MPV=-1.35 MeV, FWHM=7.406 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0.29 MeV
  mustop_pileup effective N(POT) simulated: 8.5300963e+08
  pileup: abs eff (all)=3.3622129e-06, abs eff (Edep>50)=0, avg Edep/event=3.5112 MeV, effective N(POT) simulated=8.5300963e+08
  Double-Edep expected/event (single,double,triple): 75.3286, 0.321, 0.0006
  Double-Edep estimated/event E(50,70,80,90): 0.466834, 0.00170421, 0.000542031, 0.000129194
  Rough sensitivity ce: MPV=94.5, FWHM=9, signal rate=159.406, background rate=17067800, s/sqrt(b)=0.0385849
  Rough sensitivity ce_plus: MPV=84.5, FWHM=8, signal rate=145.012, background rate=53318900, s/sqrt(b)=0.0198592
  Rough sensitivity flat_gamma: MPV=87.5, FWHM=15, signal rate=112975, background rate=97689400, s/sqrt(b)=11.4303

real    42m4.221s
user    876m5.325s
sys     39m8.627s

*** Low stats config_v21 (thin 50 mm Al center, Col5)
time python scripts/run_configuration.py config_v21 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v21/mubeam_20260411_093451
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v21/elebeam_20260411_094236
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v21/run1a_mubeam_20260411_095537
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v21/run1a_mustops_20260411_100132
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v21/mustop_20260411_094737
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v21/mustop_pileup_20260411_101212
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v21/final_20260411_101603
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00045532605
  Calorimeter absolute muon stopping rate: 4.0049264e-06
  mubeam flash output absolute efficiency: 2.062111e-05
  mubeam average Edep / event: 3.66647 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 7.471696e-06
  elebeam average Edep / event: 11.9221 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 2.8737292e-07
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 2.1956121e+08
  ce: abs eff (all)=7.0082963e-07, abs eff (Edep>50)=5.4472282e-07, MPV=-7.69 MeV, FWHM=8.274 MeV
  ce_plus: abs eff (all)=6.641656e-07, abs eff (Edep>50)=5.098806e-07, MPV=-5.96 MeV, FWHM=8.951 MeV
  flat_gamma: abs eff (all)=5.9117912e-07, abs eff (Edep>50)=4.9610312e-07, MPV=-1.45 MeV, FWHM=6 MeV
  run1a target absolute muon stopping rate: 0.0016941456
  run1a_mustops effective N(POT) simulated (per mode): 61363994
  run1a ce: eff/mu stop (all)=0.1597, eff/mu stop (Edep>50)=0.12329, abs eff (all)=0.00026025033, abs eff (Edep>50)=0.00020091587, MPV=-6.05 MeV, FWHM=11.55 MeV, trk-front fit MPV=-0 MeV, FWHM=9.93 MeV
  run1a ce_plus: eff/mu stop (all)=0.09599, eff/mu stop (Edep>50)=0.06989, abs eff (all)=0.00015642724, abs eff (Edep>50)=0.00011389415, MPV=-5.85 MeV, FWHM=5.8 MeV, trk-front fit MPV=-0 MeV, FWHM=0 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00133875, eff/mu stop (Edep>50)=0.0010485, abs eff (all)=2.1816539e-06, abs eff (Edep>50)=1.7086567e-06, MPV=-1.85 MeV, FWHM=5.9 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0.07 MeV
  mustop_pileup effective N(POT) simulated: 3.2934181e+09
  pileup: abs eff (all)=3.2057879e-06, abs eff (Edep>50)=1.5181795e-09, avg Edep/event=3.40773 MeV, effective N(POT) simulated=3.2934181e+09
  Double-Edep expected/event (single,double,triple): 96.5211, 0.5262, 0.0013
  Double-Edep estimated/event E(50,70,80,90): 0.358997, 0.00433034, 0.00102038, 0.000293256
  Rough sensitivity ce: MPV=95.5, FWHM=7, signal rate=127.123, background rate=27974600, s/sqrt(b)=0.0240348
  Rough sensitivity ce_plus: MPV=84.5, FWHM=7, signal rate=130.595, background rate=77834600, s/sqrt(b)=0.0148027
  Rough sensitivity flat_gamma: MPV=88.5, FWHM=15, signal rate=117161, background rate=1.83458e+08, s/sqrt(b)=8.64999

real    41m31.459s
user    807m39.181s
sys     26m52.482s

*** Low stats config_v22 (degrader, Al plate with 75 mm hole)
All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v22/mubeam_20260411_114725
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v22/elebeam_20260411_115505
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v22/run1a_mubeam_20260411_120901
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v22/run1a_mustops_20260411_121450
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v22/mustop_20260411_120004
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v22/mustop_pileup_20260411_122815
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v22/final_20260411_123208
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00051186368
  Calorimeter absolute muon stopping rate: 0
  mubeam flash output absolute efficiency: 8.3506976e-06
  mubeam average Edep / event: 1.88229 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 2.0116105e-06
  elebeam average Edep / event: 5.09653 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 1.9707047e+08
  ce: abs eff (all)=7.7434229e-07, abs eff (Edep>50)=4.764793e-07, MPV=-16.1 MeV, FWHM=20.93 MeV
  ce_plus: abs eff (all)=7.6711138e-07, abs eff (Edep>50)=4.2890749e-07, MPV=-16.94 MeV, FWHM=25.14 MeV
  flat_gamma: abs eff (all)=6.7526606e-07, abs eff (Edep>50)=5.1593219e-07, MPV=-1.05 MeV, FWHM=5.1 MeV
  run1a target absolute muon stopping rate: 0.0014151523
  run1a_mustops effective N(POT) simulated (per mode): 73526227
  run1a ce: eff/mu stop (all)=0.30313, eff/mu stop (Edep>50)=0.25124, abs eff (all)=0.00041227465, abs eff (Edep>50)=0.0003417012, MPV=-6.52 MeV, FWHM=6.831 MeV, trk-front fit MPV=-0.47 MeV, FWHM=0.65 MeV
  run1a ce_plus: eff/mu stop (all)=0.24937, eff/mu stop (Edep>50)=0.19849, abs eff (all)=0.00033915789, abs eff (Edep>50)=0.00026995809, MPV=-5.61 MeV, FWHM=6.64 MeV, trk-front fit MPV=-0.56 MeV, FWHM=0.73 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00185025, eff/mu stop (Edep>50)=0.001361, abs eff (all)=2.516449e-06, abs eff (Edep>50)=1.8510402e-06, MPV=-1.85 MeV, FWHM=4.702 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0.13 MeV
  mustop_pileup effective N(POT) simulated: 2.9560571e+09
  pileup: abs eff (all)=3.1004138e-06, abs eff (Edep>50)=3.3828846e-10, avg Edep/event=2.66448 MeV, effective N(POT) simulated=2.9560571e+09
  Double-Edep expected/event (single,double,triple): 32.7656, 0.0645, 0.0002
  Double-Edep estimated/event E(50,70,80,90): 0.00246698, 9.40086e-06, 4.24931e-07, 4.64603e-08
  Rough sensitivity ce: MPV=29.5, FWHM=72, signal rate=334.241, background rate=9.84248e+10, s/sqrt(b)=0.00106539
  Rough sensitivity ce_plus: MPV=66.5, FWHM=60, signal rate=298.651, background rate=9.84248e+10, s/sqrt(b)=0.000951944
  Rough sensitivity flat_gamma: MPV=72.5, FWHM=15, signal rate=105447, background rate=166034, s/sqrt(b)=258.783

real    45m1.329s
user    872m35.860s
sys     28m19.487s

*** Low stats config_v23 (degrader, Al plate with 100 mm hole)
time python scripts/run_configuration.py config_v23 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v23/mubeam_20260411_124802
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v23/elebeam_20260411_125546
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v23/run1a_mubeam_20260411_130957
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v23/run1a_mustops_20260411_131540
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v23/mustop_20260411_130046
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v23/mustop_pileup_20260411_133134
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v23/final_20260411_133524
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00051228973
  Calorimeter absolute muon stopping rate: 1.278168e-07
  mubeam flash output absolute efficiency: 8.4785144e-06
  mubeam average Edep / event: 1.88404 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 2.0116105e-06
  elebeam average Edep / event: 6.67893 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 1.9144448e+08
  ce: abs eff (all)=8.3091976e-07, abs eff (Edep>50)=5.3370565e-07, MPV=-12.36 MeV, FWHM=9.733 MeV
  ce_plus: abs eff (all)=7.9788146e-07, abs eff (Edep>50)=4.7520305e-07, MPV=-11.58 MeV, FWHM=11.71 MeV
  flat_gamma: abs eff (all)=6.8544677e-07, abs eff (Edep>50)=5.3631738e-07, MPV=-0.15 MeV, FWHM=4.801 MeV
  run1a target absolute muon stopping rate: 0.0010657277
  run1a_mustops effective N(POT) simulated (per mode): 97594302
  run1a ce: eff/mu stop (all)=0.4414, eff/mu stop (Edep>50)=0.37435, abs eff (all)=0.0004522805, abs eff (Edep>50)=0.00038357772, MPV=-6.81 MeV, FWHM=6.73 MeV, trk-front fit MPV=-0.46 MeV, FWHM=0.64 MeV
  run1a ce_plus: eff/mu stop (all)=0.37659, eff/mu stop (Edep>50)=0.30411, abs eff (all)=0.00038587294, abs eff (Edep>50)=0.00031160631, MPV=-6.09 MeV, FWHM=6.637 MeV, trk-front fit MPV=-0.54 MeV, FWHM=0.7 MeV
  run1a flat_gamma: eff/mu stop (all)=0.00205975, eff/mu stop (Edep>50)=0.0015695, abs eff (all)=2.1105228e-06, abs eff (Edep>50)=1.6081882e-06, MPV=-0.16 MeV, FWHM=5.7 MeV, trk-front fit MPV=-0.11 MeV, FWHM=0 MeV
  mustop_pileup effective N(POT) simulated: 2.8716672e+09
  pileup: abs eff (all)=3.3001735e-06, abs eff (Edep>50)=6.9645954e-10, avg Edep/event=2.71526 MeV, effective N(POT) simulated=2.8716672e+09
  Double-Edep expected/event (single,double,triple): 35.5303, 0.0771, 0.0001
  Double-Edep estimated/event E(50,70,80,90): 0.0125984, 7.68566e-05, 5.59702e-06, 8.74424e-07
  Rough sensitivity ce: MPV=90.5, FWHM=71, signal rate=367.177, background rate=1.32388e+11, s/sqrt(b)=0.00100914
  Rough sensitivity ce_plus: MPV=75.5, FWHM=60, signal rate=326.467, background rate=1.58644e+11, s/sqrt(b)=0.000819647
  Rough sensitivity flat_gamma: MPV=74.5, FWHM=15, signal rate=106229, background rate=1620040, s/sqrt(b)=83.4608

real    47m40.758s
user    907m47.599s
sys     28m25.767s

*** Low stats config_v24 (degrader, Al plate with 125 mm hole)
time python scripts/run_configuration.py config_v24 30 --stage all --mustop-events-per-job 10000 --mustop-pileup-events-per-job 50000 --events-per-job 10000 --elebeam-events-per-job 10000 --run1a-mubeam-events-per-job 5000

All-stage sequence complete. mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v24/mubeam_20260416_101315
All-stage sequence complete. elebeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v24/elebeam_20260416_102136
All-stage sequence complete. run1a_mubeam run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v24/run1a_mubeam_20260416_103730
All-stage sequence complete. run1a_mustops run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v24/run1a_mustops_20260416_104307
All-stage sequence complete. mustop run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v24/mustop_20260416_102638
All-stage sequence complete. mustop_pileup run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v24/mustop_pileup_20260416_110117
All-stage sequence complete. final run: /exp/mu2e/app/users/mmackenz/run1b/Run1BAna/workflows/runs/config_v24/final_20260416_110511
-----
Compact all-stage summary
  Target absolute muon stopping rate: 0.00050960558
  Calorimeter absolute muon stopping rate: 0
  mubeam flash output absolute efficiency: 8.9897816e-06
  mubeam average Edep / event: 1.68396 MeV
  mubeam events with Edep > 50 per simulated event (absolute): 0
  mubeam effective N(POT) simulated: 23471093
  elebeam flash output absolute efficiency: 4.8853397e-06
  elebeam average Edep / event: 7.35183 MeV
  elebeam events with Edep > 50 per simulated event (absolute): 0
  elebeam effective N(POT) simulated: 3479799
  mustop effective N(POT) simulated (per mode): 1.9740196e+08
  ce: abs eff (all)=8.0255029e-07, abs eff (Edep>50)=5.3140303e-07, MPV=-13.46 MeV, FWHM=9.186 MeV
  ce_plus: abs eff (all)=7.7836107e-07, abs eff (Edep>50)=4.8201143e-07, MPV=-11.02 MeV, FWHM=9.496 MeV
  flat_gamma: abs eff (all)=6.6628011e-07, abs eff (Edep>50)=5.2925007e-07, MPV=-1.75 MeV, FWHM=6.6 MeV
  run1a target absolute muon stopping rate: 0.0008122978
  run1a_mustops effective N(POT) simulated (per mode): 1.2757942e+08
  run1a ce: eff/mu stop (all)=0.56104, eff/mu stop (Edep>50)=0.48156, abs eff (all)=0.00043975746, abs eff (Edep>50)=0.00037745901, MPV=-7.41 MeV, FWHM=6.631 MeV, trk-front fit MPV=-0.46 MeV, FWHM=0.64 MeV
  run1a ce_plus: eff/mu stop (all)=0.48654, eff/mu stop (Edep>50)=0.39484, abs eff (all)=0.00038136246, abs eff (Edep>50)=0.00030948566, MPV=-6.3 MeV, FWHM=5.546 MeV, trk-front fit MPV=-0.55 MeV, FWHM=0.71 MeV
  run1a flat_gamma: eff/mu stop (all)=0.002265, eff/mu stop (Edep>50)=0.001783, abs eff (all)=1.7753648e-06, abs eff (Edep>50)=1.3975609e-06, MPV=-1.25 MeV, FWHM=4.9 MeV, trk-front fit MPV=-0.1 MeV, FWHM=0 MeV
  mustop_pileup effective N(POT) simulated: 2.9610294e+09
  pileup: abs eff (all)=3.3920636e-06, abs eff (Edep>50)=1.0131612e-09, avg Edep/event=2.87094 MeV, effective N(POT) simulated=2.9610294e+09
  Double-Edep expected/event (single,double,triple): 53.2823, 0.1681, 0.0004
  Double-Edep estimated/event E(50,70,80,90): 0.00541195, 0.000244371, 4.2114e-06, 7.51832e-07
  Rough sensitivity ce: MPV=89.5, FWHM=15, signal rate=129.871, background rate=827034, s/sqrt(b)=0.142808
  Rough sensitivity ce_plus: MPV=79.5, FWHM=58, signal rate=320.226, background rate=2.28418e+11, s/sqrt(b)=0.000670027
  Rough sensitivity flat_gamma: MPV=72.5, FWHM=15, signal rate=112703, background rate=2633170, s/sqrt(b)=69.4537

real    52m13.800s
user    945m5.924s
sys     28m27.390s
